### Get all locations
GET http://localhost:8080/api/locations


### Create location
POST http://localhost:8080/api/locations
Content-Type: application/json

{
    "name": "own",
    "room": "BASEMENT"
}


### Update location description
PUT http://localhost:8080/api/locations/1
Content-Type: application/json

{
    "info": "befolyt a víz, nedves"
}


### Delete location by ID
DELETE http://localhost:8080/api/locations/1


### Get location names
GET http://localhost:8080/api/locations/names


### Get location rooms by name
GET http://localhost:8080/api/locations/own/rooms


### Get location things by ID
GET http://localhost:8080/api/locations/2/things