### Get all things
GET http://localhost:8080/api/things


### Create thing
POST http://localhost:8080/api/things
Content-Type: application/json

{
    "locationId": 1,
    "description": "drót csiszoló korong",
    "type": "HAND_TOOL"
}


### Update thing description
PUT http://localhost:8080/api/things/1/description
Content-Type: application/json

{
    "description": "drót csiszoló korong M14"
}

### Update thing location
PUT http://localhost:8080/api/things/1/location
Content-Type: application/json

{
    "locationId": "2"
}


### Delete thing by ID
DELETE http://localhost:8080/api/things/3

### List filtered things
GET http://localhost:8080/api/things?type=HAND_TOOL&description=28mm

### Upload picture
POST http://localhost:8080/api/things/1/picture
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="picture.jpeg"

// The picture file will be uploaded
< pic/IMG_20220629_095936.jpg

1
--WebAppBoundary

###
GET http://localhost:8080/api/things/last-moved?count=1&location-id=1