### Get all things
GET http://localhost:8080/api/things


### Create thing
POST http://localhost:8080/api/things
Content-Type: application/json

{
    "locationId": 1,
    "description": "28mm kulcs",
    "type": "HAND_TOOL"
}


### Update thing description
PUT http://localhost:8080/api/things/1/description
Content-Type: application/json

{
    "description": "töltö 6V"
}

### Update thing location
PUT http://localhost:8080/api/things/1/location
Content-Type: application/json

{
    "locationId": "2"
}


### Delete thing by ID
DELETE http://localhost:8080/api/things/3

### List filtered things
GET http://localhost:8080/api/things?type=HAND_TOOL&description=28mm

### gdfg dfgdf
GET http://localhost:8080/api/things/own/rooms

###
POST http://localhost:8080/api/things/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="data"; filename="data.json"
Content-Type: application/json

< ./request-form-data.json
--WebAppBoundary--