package inventory.model.enums;

public enum RoomName {
    
    OTHER,

    HOUSE, HOUSE_ATTIC, GARAGE, GARAGE_ATTIC, SHED,

    PARENT_HOUSE, PARENT_HOUSE_ATTIC, PARENT_GARAGE, PARENT_GARAGE_ATTIC, PARENT_SHED,

    VACATION_HOUSE, VACATION_HOUSE_SHED

}
